name: BasicEconomy
main: main.java.com.trophonix.basiceconomy.Main
version: 1.0
author: Trophonix
commands:
   beco:
      description: Administrative command for BasicEconomy
      usage: /<command> args
      aliases: basiceconomy
   pay:
      description: Pay people money
      usage: /<command> player_name amount
   balance:
      description: Tells you your current balance
      usage: /<command>
      aliases: [money,bal]